require('items.right_items.calendar')
require('items.right_items.keyboard-layout')
require('items.right_items.battery')
require('items.right_items.volume')
require('items.right_items.spotify-app')
--require('items.right_items.spotify-player')
require('items.right_items.timew')
