[settings]
animate = false
focus_follows_mouse = false
mouse_follows_focus = true
mouse_hides_on_focus = false
hot_reload = true
default_disable = false

run_on_start = [
  "rift-cli subscribe cli --event workspace_changed --command sh --args -c --args 'sketchybar --trigger rift_workspace_changed FOCUSED_WORKSPACE=\"$RIFT_WORKSPACE_NAME\" RIFT_WORKSPACE_ID=\"$RIFT_WORKSPACE_ID\"'",
  #"rift-cli subscribe cli --event windows_changed --command sh --args -c --args 'sketchybar --trigger rift_windows_changed FOCUSED_WORKSPACE=\"$RIFT_WORKSPACE_NAME\" RIFT_WINDOW_COUNT=\"$RIFT_WINDOW_COUNT\"'"
  "media-stream",
  "sketchybar",
]

[settings.gestures]
enabled = true
invert_horizontal_swipe = true
swipe_vertical_tolerance = 0.4
skip_empty = true
fingers = 3
distance_pct = 0.08
haptics_enabled = false

[settings.layout]
mode = "stack"

[settings.layout.stack]
stack_offset = 0.0
default_orientation = "perpendicular"

[settings.layout.gaps.outer]
top = 37
left = 0
bottom = 0
right = 0

[settings.layout.gaps.inner]
horizontal = 5
vertical = 5

[virtual_workspaces]
enabled = true
default_workspace_count = 6
default_workspace = 3
auto_assign_windows = true
preserve_focus_per_workspace = true
workspace_auto_back_and_forth = true

workspace_names = ["chats", "music", "personal", "terminal", "work", "zone"]

#workspace_rules = [
#  { workspace = 0, layout = "master_stack" },
#  { workspace = 1, layout = "master_stack" },
#  { workspace = 2, layout = "master_stack" },
#  { workspace = 3, layout = "master_stack" },
#  { workspace = 4, layout = "master_stack" },
#  { workspace = 5, layout = "master_stack" },
#]

app_rules = [
  { ax_subrole = "AXDialog", floating = true },
  { title_regex = "floating", floating = true },
  { app_id = "com.objective-see.lulu.app", floating = true },

  { app_id = "org.whispersystems.signal-desktop", workspace = "chats" },
  { app_id = "com.apple.MobileSMS", workspace = "chats" },
  { app_id = "net.whatsapp.WhatsApp", workspace = "chats" },
  { app_id = "com.viber.osx", workspace = "chats" },
  { app_name = "Slack", workspace = "chats" },
  { app_name = "Discord", workspace = "chats" },
  { app_name = "WhatsApp Web", workspace = "chats" },
  { app_name = "Messenger", workspace = "chats" },

  { app_id = "com.github.wez.wezterm", workspace = "terminal" },
  { app_id = "com.mitchellh.ghostty", workspace = "terminal" },
  { app_id = "net.kovidgoyal.kitty", workspace = "terminal" },

  { app_id = "com.spotify.client", workspace = "music" },
  { app_name = "Spotify", workspace = "music" },
  { app_name = "YouTube", workspace = "music" },

  { app_id = "com.vivaldi.Vivaldi", workspace = "personal" },
  { app_id = "com.brave.Browser", title_substring = "personal", workspace = "personal" },

  { app_id = "com.brave.Browser", title_substring = "work", workspace = "work" },

  { app_id = "com.brave.Browser", title_substring = "zone", workspace = "zone" },

  { app_id = "com.apple.finder", floating = true },
  { app_id = "com.brave.Browser", title_substring = "Bitwarden", floating = true },
  { app_id = "com.alienator88.Pearcleaner", floating = true },
  { app_id = "com.apple.iCal", floating = true },
  { app_id = "com.getcoldturkey.blocker", floating = true },
  { app_id = "net.kovidgoyal.calibre", floating = true },
  { app_id = "com.apple.iWork.Numbers", floating = true },

  { app_id = "com.apple.systempreferences", floating = true },

  { title_regex = "WireGuard", floating = true },
  { title_regex = "LuLu Alert", floating = true },
  { title_regex = "file-search", floating = true },
]

[modifier_combinations]
move = "Alt + Shift"

[keys]

"Meta + Shift + W" = { exec = "kitty --title floating-window -e change-wallpaper" }
"Meta + Shift + S" = { exec = "kitty --title floating-window -e file-search" }
"Alt + F" = { exec = "open /Users/cujanovic/Downloads" }
"Meta + Space" = { exec = "app-launcher" }

"Alt + H" = { move_focus = "left" }
"Alt + J" = { move_focus = "down" }
"Alt + K" = { move_focus = "up" }
"Alt + L" = { move_focus = "right" }

"move + H" = { move_node = "left" }
"move + J" = { move_node = "down" }
"move + K" = { move_node = "up" }
"move + L" = { move_node = "right" }

"Alt + C" = { switch_to_workspace = 0 } # chats
"Alt + M" = { switch_to_workspace = 1 } # music
"Alt + P" = { switch_to_workspace = 2 } # personal
"Alt + T" = { switch_to_workspace = 3 } # terminal
"Alt + W" = { switch_to_workspace = 4 } # work
"Alt + Z" = { switch_to_workspace = 5 } # zone

"Meta + Shift + R" = { exec = "rift service restart" }

"move + C" = { move_window_to_workspace = 0 }
"move + M" = { move_window_to_workspace = 1 }
"move + P" = { move_window_to_workspace = 2 }
"move + T" = { move_window_to_workspace = 3 }
"move + W" = { move_window_to_workspace = 4 }
"move + Z" = { move_window_to_workspace = 5 }

"Alt + Enter" = "switch_to_last_workspace"

"Alt + Comma" = "toggle_stack"

"Alt + Period" = "toggle_orientation"

"Meta + Shift + F" = "toggle_fullscreen"

"Ctrl + Meta + K" = "resize_window_grow"
"Ctrl + Meta + J" = "resize_window_shrink"

"Alt + Shift + Left" = { join_window = "left" }
"Alt + Shift + Right" = { join_window = "right" }
"Alt + Shift + Up" = { join_window = "up" }
"Alt + Shift + Down" = { join_window = "down" }

"Alt + Shift + Space" = "toggle_window_floating"
