local sf_symbols = {
    airpod_left = '􀲎',
    airpod_right = '􀲍',
    airpods = '􀪷',
    airpods_case = '􀹬',
    battery = '󰁹',
    battery_25 = '􀛩',
    battery_50 = '􀺶',
    battery_75 = '􀺸',
    battery_charging = '􀢋',
    battery_empty = '􀛪',
    battery_full = '􀛨',
    calendar = '􀧞',
    charging = '󱐋',
    clock = '􀐫',
    headphones = '􀑈',
    mac_mini = '􂶹',
    hide = '􀋯',
    keyboard = '􀇳',
    laptop = '􀟛',
    media_icon = '􀑪',
    monitor = '􀢹',
    next = '􀊏',
    pause = '􀊅',
    play = '􀊃',
    previous = '􀊍',
    reset = '􀅉',
    --separator = '􀆊',
    separator = '􀆓',
    show = '􀋭',
    speaker = '􀝎',
    stop = '􀛶',
    viber = '', --this one is taken from nerdfont
    volume_25 = '􀊠',
    volume_50 = '􀊤',
    volume_full = '􀊦',
    volume_mute = '􀊢',
}

local default = sf_symbols

return default
