#!/usr/bin/env lua

os.execute(
    '[ ! -d $HOME/.local/share/sketchybar_lua/ ] && '
        .. '(git clone https://github.com/FelixKratz/SbarLua.git /tmp/SbarLua && cd /tmp/SbarLua/ && make install)'
)

package.cpath = package.cpath .. ';' .. os.getenv('HOME') .. '/.local/share/sketchybar_lua/?.so'

local sbar = require('sketchybar')
sbar.begin_config()

local events = require('events')
require('bar')

events.setup_events()
require('items') -- items must be loaded in between
events.trigger_events()

sbar.hotload(true)
sbar.end_config()
sbar.event_loop()
