[[themes]]
name = "gruvbox_dark"
[themes.palette]
black = "#282828"
red = "#9d0006"
green = "#79740e"
yellow = "#b57614"
magenta = "#b16286"
cyan = "#689d6a"
white = "#a89984"
bright_black = "#928374"
bright_red = "#fb4934"
bright_green = "#b8bb26"
bright_yellow = "#fabd2f"
bright_blue = "#83a598"
bright_magenta = "#d3869b"
bright_cyan = "#8ec07c"
bright_white = "#ebdbb2"

[themes.component_style]
selection = { bg = "Green" }
block_title = { fg = "Yellow" }
playback_track = { fg = "Blue" }
playback_album = { fg = "Red" }
playback_metadata = { fg = "#fe8019" }
playback_progress_bar = { fg = "Green" }
current_playing = { fg = "BrightYellow" }
#page_desc = { fg = "Cyan", modifiers = ["Bold"] }
#table_header = { fg = "Blue", modifiers = ["Bold"]}
border = { fg = "Green"}
playback_status = { fg = "BrightRed" }
playback_artists = { fg = "BrightYellow" }
playlist_desc = { fg = "Green" }
lyrics_played = { fg = "Green" }
